### ISSUE TITLE
Add LMesh.jl?

### ISSUE THREAD

**Issue by mauro3** [JuliaGeometry/meta#4]
@njwilson23 and I have this (partial) implementation of Logg 2012 mesh, which is what FEnICS uses:
https://bitbucket.org/maurow/lmesh.jl

Any interest in adding this to JuliaGeometry?

**Comment by sjkelly** [comment]
Maybe we could add this representation to GeometryTypes or Meshes if some of the dependencies get sorted out. In the mean time would you want to move it here for better visibility?
