### ISSUE TITLE
JuliaGeometry meetup?

### ISSUE THREAD

**Issue by yeesian** [JuliaGeometry/meta#5]
After the [extrication of geometries from Base](https://github.com/JuliaLang/julia/issues/9862), I think there's been development that took place across enough packages, e.g. 

- https://github.com/JuliaLang/Graphics.jl
- https://github.com/nolta/Winston.jl
- https://github.com/JuliaGeometry/GeometryTypes.jl
- https://github.com/JuliaGeometry/GeometricalPredicates.jl
- https://github.com/dcjones/Compose.jl
- https://github.com/JuliaGeo/GeoInterface.jl
- https://github.com/JuliaGeo/LibGEOS.jl
- https://github.com/Keno/Shapefile.jl
- https://github.com/zyedidia/SFML.jl

for us to want to re-visit the conversation again, and hash things out abit. I'll talk more about it tomorrow (in the talk on JuliaGeo), but in the meantime it'll be good to start getting responses for a meetup for julia developers who're in the Boston area.

**(Tentative) Date/time**: Saturday, 27 June 2015, 10 AM

Do reply with the dates/times of your availability, so I can book a room.

cc: @dcjones @SimonDanisch @sjkelly @wkearn @jminardi @timholy @shashi @Keno @lobingera @ViralBShah @rohitvarkey @KristofferC @garborg @randyzwitch @jheinen @tedsteiner @zyedidia, others?

**Comment by yeesian** [comment]
AFAIK Here's a collection of the conversations that have taken place:

- https://github.com/JuliaGeo/LibGEOS.jl/pull/6
- https://github.com/JuliaGeometry/GeometryTypes.jl/issues/3
- https://github.com/rohitvarkey/Compose3D.jl/issues/2

**Comment by IainNZ** [comment]
(if you make it a bring-your-own-lunch meeting, you can avoid workshops)

**Comment by randyzwitch** [comment]
I’m fine with lunch meeting

**Comment by SimonDanisch** [comment]
Me too... Lets do this =)

**Comment by lobingera** [comment]
Thanks for inviting me. I wish everyone a fruitful meeting. Unfortunately there is some physical distance between myself and the meeting...

**Comment by dcjones** [comment]
Lunch meeting works for me.

**Comment by sjkelly** [comment]
I will be gone on Saturday. Please take minutes so we can all stay up to date. I also proposed doing a monthly google hangout. Maybe we could schedule one in about 2 weeks as well?

**Comment by rohitvarkey** [comment]
Sorry, won't be able to make it. Not in Boston. I'm up for the hangout though!

**Comment by jiahao** [comment]
I have reserved the videoconference room 32-262 for this working group, Saturday 9:30am-7pm. People will need keycard access... we'll have to figure out something.

**Comment by jheinen** [comment]
Lunch meeting would be OK for me - but I have to leave by 13:00 ...

**Comment by shashi** [comment]
Will be there. :+1:

**Comment by jminardi** [comment]
I will be there Saturday as well

On Thursday, June 25, 2015, Shashi Gowda <notifications@github.com> wrote:

> Will be there. [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JuliaGeometry/meta/issues/5#issuecomment-115450762>.
>


-- 
Jack Minardi
jack.minardi.org
jack@minardi.org

**Comment by zyedidia** [comment]
I'll be there Saturday, and slightly prefer lunch time.

**Comment by yeesian** [comment]
Let's meet at 12noon then. Don't forget to bring your own lunch!

**Comment by yeesian** [comment]
> I will be gone on Saturday. Please take minutes so we can all stay up to date. I also proposed doing a monthly google hangout. Maybe we could schedule one in about 2 weeks as well?

Yeah sure, shall we put it in the wiki on this repository or sth?

**Comment by jiahao** [comment]
For those looking for the conference room, please follow the Julia signs from the Dreyfoos elevator lobby.

**Comment by yeesian** [comment]
Hey everyone, I'll be going down to the room now. You can reach me at (857) 999-1805 if you're there and need access.

**Comment by yeesian** [comment]
Sorry I'm still out stuck in a lunch queue. Simon is alr there, so please feel free to post here if you need access, and start (introducing yourselves/etc) without me

**Comment by zyedidia** [comment]
Hi, I'm having trouble getting to the room. The door near the elevators is locked and I can't get in. Thanks!

**Comment by sjkelly** [comment]
@dcjones thanks for posting minutes!

I have purchased JuliaGeometry.com/org and I think we could start advertising our objectives a little bit better with a website. Would everyone be up for a recurring monthly video chat to stay in sync?

**Comment by lobingera** [comment]
@sjkelly ... dcjones posting minutes
Pardon my ignorance, but where?

**Comment by rohitvarkey** [comment]
@lobingera The minutes have been put up on the Wiki of the meta repository. You can find them [here](https://github.com/JuliaGeometry/meta/wiki/First-Meetup-Minutes).

**Comment by yeesian** [comment]
> I have purchased JuliaGeometry.com/org and I think we could start advertising our objectives a little bit better with a website. Would everyone be up for a recurring monthly video chat to stay in sync?

Sure! I'm not sure I'll be developing regularly enough to have updates each month, but it'll be nice to stay in touch in some way.

The gist of the meetup so far's that we don't yet have a good way of reconciling each other's concerns (even though we did get to understand where everyone else is coming from). We'll still have to play around abit and see how things play out.

**Comment by yeesian** [comment]
@sjkelly, shall we open up a separate issue for the next meetup? I'll close this one.

**Comment by sjkelly** [comment]
@yeesian great! See https://github.com/JuliaGeometry/meta/issues/6
